# IsiDetector — Windows bootstrap (CPU-only).
#
# Mirrors the Stage 6 build step from deploy/_impl/run_start.sh, but
# skips everything Linux-specific:
#   - no `apt` / Docker Engine install (Docker Desktop handles that)
#   - no docker-group / sudo dance (Docker Desktop runs as the user)
#   - no NVIDIA toolkit (CPU-only by spec for Windows site PCs)
#   - no GPU detection (always CPU)
#
# Run once per host after install.ps1 has set up Docker Desktop.
# Re-running rebuilds the image (cached layers are reused, so it's
# ~10s on a no-op rebuild).

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$RepoRoot  = (Resolve-Path (Join-Path $ScriptDir "..\..")).Path
$DeployDir = (Resolve-Path (Join-Path $ScriptDir "..")).Path
Set-Location $DeployDir

Write-Host ""
Write-Host "═══════════════════════════════════════════════════" -ForegroundColor White
Write-Host "  IsiDetector — Windows Bootstrap (CPU)" -ForegroundColor White
Write-Host "═══════════════════════════════════════════════════" -ForegroundColor White
Write-Host ""

# ── Pre-flight: Docker engine reachable ─────────────────────────────────────
docker info > $null 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "[FAIL] Docker engine not reachable." -ForegroundColor Red
    Write-Host "       Start Docker Desktop from the Start menu, wait until the whale icon" -ForegroundColor Red
    Write-Host "       in the system tray turns solid (not animating), then re-run." -ForegroundColor Red
    Set-Location $RepoRoot
    exit 1
}
$dockerVer = (docker version --format '{{.Server.Version}}' 2>$null)
Write-Host "[ OK ] Docker engine reachable (server $dockerVer)" -ForegroundColor Green

# ── Build CPU image ─────────────────────────────────────────────────────────
Write-Host ""
Write-Host "[INFO] Building Docker image (Dockerfile.cpu)..." -ForegroundColor Cyan
Write-Host "       First build takes 2-4 minutes; cached rebuilds are ~10s." -ForegroundColor DarkCyan
& docker compose -f docker-compose.yml -f docker-compose.cpu.yml build
if ($LASTEXITCODE -ne 0) {
    Write-Host "[FAIL] Image build failed. Check the lines above for the underlying error." -ForegroundColor Red
    Set-Location $RepoRoot
    exit 1
}
Write-Host "[ OK ] Docker image ready" -ForegroundColor Green

# ── Persist deployment profile ──────────────────────────────────────────────
# up.sh on Linux reads .deployment.env to pick the compose file; up.ps1
# is hard-coded CPU but we still write the marker so a Linux user who
# later boots the same WSL filesystem sees a coherent state.
$markerPath = Join-Path $DeployDir ".deployment.env"
@"
# Auto-generated by deploy/windows/run_start.ps1 — do not edit.
COMPOSE_MODE=cpu
SUDO_DOCKER=
"@ | Set-Content -Path $markerPath -Encoding ASCII
Write-Host "[ OK ] Deployment marker: $markerPath" -ForegroundColor Green

# ── Runtime directories ─────────────────────────────────────────────────────
# Volumes are created on first compose-up, but pre-creating them avoids
# permission surprises and matches the Linux run_start.sh behaviour.
$runtimeDirs = @(
    "isidet\models", "isidet\configs", "isidet\runs", "isidet\logs",
    "isidet\logs\events",
    "webapp\isitec_app\logs", "webapp\isitec_app\uploads"
)
foreach ($d in $runtimeDirs) {
    $full = Join-Path $RepoRoot $d
    if (-not (Test-Path $full)) {
        New-Item -ItemType Directory -Force -Path $full | Out-Null
    }
}
Write-Host "[ OK ] Runtime directories ready" -ForegroundColor Green

# ── Summary ─────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "═══════════════════════════════════════════════════" -ForegroundColor White
Write-Host "  IsiDetector — Bootstrap Complete" -ForegroundColor White
Write-Host "═══════════════════════════════════════════════════" -ForegroundColor White
Write-Host ""
Write-Host "  Dashboard:    http://localhost:9501"
Write-Host "  Docs:         http://localhost:9501/docs"
Write-Host "  UDP Target:   127.0.0.1:9502"
Write-Host ""
Write-Host "  Drop model weights into:" -ForegroundColor DarkCyan
Write-Host "    $RepoRoot\isidet\models\" -ForegroundColor DarkCyan
Write-Host ""
Write-Host "  Daily start:  double-click Start.bat   (or run deploy\windows\up.ps1)"
Write-Host ""

Set-Location $RepoRoot
